spring:
  application:
    name: manage_project

  datasource:
    url: jdbc:mysql://localhost:3306/manage_project?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: "06032005"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8081

jwt:
  expiration: 3600000
  secret: Re9fmTCczOChSZt1tlftE50nKO3NaJiKS6PgVTT4UK2